# Generated by Django 5.2.13 on 2026-04-26 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tattooer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('artistic_style', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('waiting_budget', 'Aguardando Orcamento'), ('confirmed', 'Sessao Confirmada'), ('in_progress', 'Em Andamento'), ('done', 'Concluido'), ('cancelled', 'Cancelado')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='studio.client')),
                ('tattooer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='studio.tattooer')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
