# Generated by Django 5.2.13 on 2026-05-11 23:03

from django.db import migrations, models


def backfill_change_request_payload(apps, schema_editor):
    AppointmentChangeRequest = apps.get_model("studio", "AppointmentChangeRequest")
    for cr in AppointmentChangeRequest.objects.all().iterator():
        payload = cr.proposed_payload or {}
        if not payload and cr.proposed_scheduled_at:
            cr.proposed_payload = {
                "scheduled_at": cr.proposed_scheduled_at.isoformat(),
            }
            cr.save(update_fields=["proposed_payload"])


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_studiosettings_appointment_appointment_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="appointmentchangerequest",
            name="proposed_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="appointmentchangerequest",
            name="proposed_reference_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="appointment_change_refs/"
            ),
        ),
        migrations.AlterField(
            model_name="appointmentchangerequest",
            name="proposed_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_change_request_payload, migrations.RunPython.noop),
    ]
